CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE Board (
  id INT AUTO_INCREMENT PRIMARY KEY,
  length INT NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE Tile (
  id INT AUTO_INCREMENT PRIMARY KEY,
  boardId INT NOT NULL,
  position INT NOT NULL,
  pairPosition INT NULL,
  value INT NOT NULL,
  FOREIGN KEY (boardId) REFERENCES Board(id) ON DELETE CASCADE
);
